# Generated by Django 5.2.1 on 2025-06-01 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrecipitationRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(help_text="Date of the precipitation record"),
                ),
                ("precipitation", models.FloatField(blank=True, null=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="precipitation_records",
                        to="dashboard_app.africancity",
                    ),
                ),
            ],
            options={
                "ordering": ["date"],
                "unique_together": {("city", "date")},
            },
        ),
    ]
