# Generated by Django 5.2.1 on 2025-06-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_app", "0002_precipitationrecords"),
    ]

    operations = [
        migrations.AddField(
            model_name="africancity",
            name="population",
            field=models.BigIntegerField(
                blank=True, help_text="Latest population (from OWM)", null=True
            ),
        ),
    ]
