# Generated by Django 5.2.1 on 2025-06-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_app", "0003_africancity_population"),
    ]

    operations = [
        migrations.AddField(
            model_name="africancity",
            name="warning_level",
            field=models.CharField(
                choices=[("green", "Green"), ("orange", "Orange"), ("red", "Red")],
                default="green",
                help_text="Precomputed 4-day precipitation warning",
                max_length=6,
            ),
        ),
        migrations.AlterField(
            model_name="africancity",
            name="population",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
