# Generated by Django 5.2.1 on 2025-06-06 13:17

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_app", "0005_testgeo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Watershed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Human-readable name for this watershed",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True,
                        help_text="Polygon geometry of the watershed (EPSG:4326)",
                        null=True,
                        srid=4326,
                    ),
                ),
                (
                    "warning_level",
                    models.CharField(
                        choices=[
                            ("green", "Green"),
                            ("orange", "Orange"),
                            ("red", "Red"),
                        ],
                        default="green",
                        help_text="Precomputed 4-day precipitation warning for the watershed",
                        max_length=6,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="africancity",
            name="latitude",
        ),
        migrations.RemoveField(
            model_name="africancity",
            name="longitude",
        ),
        migrations.AddField(
            model_name="africancity",
            name="location",
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True,
                help_text="Exact lat/lon (EPSG:4326) of this city",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AddField(
            model_name="africancity",
            name="watershed",
            field=models.ForeignKey(
                blank=True,
                help_text="Which watershed this city is in (if known)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cities",
                to="dashboard_app.watershed",
            ),
        ),
    ]
