# Generated by Django 5.2.1 on 2025-06-06 16:47

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_app", "0006_watershed_remove_africancity_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watershed",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                help_text="Watershed boundary (MultiPolygon) in EPSG:4326",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="watershed",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="watershed",
            name="warning_level",
            field=models.CharField(
                choices=[("green", "Green"), ("orange", "Orange"), ("red", "Red")],
                default="green",
                help_text="4-day precipitation warning for the watershed",
                max_length=6,
            ),
        ),
    ]
