# Generated by Django 5.2.1 on 2025-06-06 16:51

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard_app", "0007_alter_watershed_geom_alter_watershed_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watershed",
            name="geom",
            field=django.contrib.gis.db.models.fields.MultiPolygonField(
                blank=True,
                help_text="Watershed boundary (MULTIPOLYGON) in EPSG:4326",
                null=True,
                srid=4326,
            ),
        ),
        migrations.AlterField(
            model_name="watershed",
            name="name",
            field=models.CharField(
                help_text="Human-readable name for this watershed (filename without .shp)",
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="watershed",
            name="warning_level",
            field=models.CharField(
                choices=[("green", "Green"), ("orange", "Orange"), ("red", "Red")],
                default="green",
                help_text="Precomputed 4-day precipitation warning for the watershed",
                max_length=6,
            ),
        ),
    ]
